floor_1: "/home/mobinn/urop_ws/src/multi_floor_global_planner/snu_localization/map/ver2_303_map/303_1f_ver2.pcd"
floor_2: "/home/mobinn/urop_ws/src/multi_floor_global_planner/snu_localization//map/ver2_303_map/303_2f_ver2.pcd"
floor_3: "/home/mobinn/urop_ws/src/multi_floor_global_planner/snu_localization//map/ver2_303_map/303_3f_ver2.pcd"

I_L_extrinsic: [1.0, 0.0, 0.0, -0.011,
                0.0, 1.0, 0.0, -0.02329,
                0.0, 0.0, 1.0, 0.04412,
                0.0, 0.0, 0.0, 1.0]   


NDT_voxel_size: 0.8
scan_voxel_size: 0.3
map_voxel_size: 0.3
map_entire_voxel_size: 0.2

pcd_save:
    pcd_save_en: true
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
